---
title: "ggplot and plot.ly"
output: html_document
---

# Mapping Crime in NYC

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# Load packages
library(knitr)

# Get data on NYC police complaints
library(readr)
nypd <- read_csv("data/NYPD_Complaint_2016-12_Manhattan.csv")
```

## Crime by type - Data Table

```{r, eval=TRUE, message=FALSE, warning=FALSE, echo=FALSE}
# Get data on NYC police complaints
library(readr)
nypd <- read_csv("data/NYPD_Complaint_2016-12_Manhattan.csv")
```

Take a look at the data with a `datatable`:

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(dplyr)
library(DT)
datatable(dplyr::select(nypd, date, offense_desc1, crimelevel, premise_type))
```

## Crime by type - ggplot

Not interactive plots are easy to add.

```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
# Selected offenses
# sort(table(nypd$offense_desc1))
off <- nypd$offense_desc1 
offsel <- NA
offsel <- ifelse(off=="GRAND LARCENY" | off=="PETIT LARCENY" | off=="THEFT-FRAUD" | off=="THEFT OF SERVICES", "Theft", offsel)
offsel <- ifelse(off=="HARRASSMENT", "Harrassment", offsel)
offsel <- ifelse(off=="ASSAULT 3 & RELATED OFFENSES" | off=="FELONY ASSAULT", "Assault", offsel)
offsel <- ifelse(off=="DANGEROUS DRUGS", "Drugs", offsel)
offsel <- ifelse(is.na(offsel), "Other Crime", offsel)
nypd$offsel1 <- offsel
```

```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(ggthemes)
g <- ggplot(nypd, aes(offsel1, fill=offsel1)) + geom_bar() + theme_economist() + coord_flip() +
  labs(title = "Crime in NYC", subtitle= "I spent about 20s making this graphs - it shows") +
  theme(axis.title=element_blank())
g
```

## Crime by type - plot.ly works too

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(plotly)
ggplotly(g)
```

